### ISSUE TITLE
Add Leaderboard for Counting

### ISSUE THREAD

**Issue by Sanjit1** [Sanjit1/Co26UCLAbot#5]
Add Leaderboard for counting.
Point system.
Track each statistic.
+10 points for each number counter
+100 points for numbers counted that end with 00.
+69 points for numbers counted that end with 69.
-20 points for wrong counts.

Commands:
j!count top: returns top 10 counters.
j!count rank <person>: counting rank.
j!count stats <person>: statistics based on trackerss mentioned above.

Other things affected:
j!help: Add new commands to help line.

Implementation for tracking points:
modules/storage/counting.json: 
"users": [
"person":{
"rank": 1,
"counts": 4,
"Hundies": 1,
"Nices'": 9,
"score": 324
}
]

**Comment by leonlenk** [comment]
We should just calculate the rank each time leaderboard is called instead of storing it, and for the point system something like:
+10 for counting
+69 for  n % 100 == 69
+ 100 for n%100 == 0
+42 for n%100 == 42 //the answer to life the universe and everything hitchhikers guide to the galaxy
+ 42 for n%1000 == 420
- ax for wrong count where we get x from the number subtracted from the count and where a is some factor where it starts as 1 but then increases by .1 for every fail they have or something so that repeat offenders have a really low score

**Comment by leonlenk** [comment]
For clarity should probably also make this
modules/storage/counting.json:
"countingScores": [
"UserID": 1231231123
"timesCounted": 4
"timesCountedHundred": 1
"timesCountedSixtyNine'": 9
"timesCountedFourTwenty":1
"timesCountedFourtyTwo":1
"errorsInCounting": 4
"currentScore": 29,
]
So I think we should save everything about a person in one indice of the array and use some scheme like * and : to seperate the values of each number we care about so that it's easy to calculate someones score
